version: "3.9"
services:

  server:
    build:
      context: .
      dockerfile: Dockerfile.serving
    ports:
      - "8080:8080"

  web:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"